VARIABLE A_LOW
VARIABLE A_HIGH
VARIABLE B_LOW
VARIABLE B_HIGH
VARIABLE CARRY_VAR

VARIABLE UNSIGNED_MASK
VARIABLE VAL_A
VARIABLE VAL_B

: CR 10 EMIT ;
: DIGIT>CHAR 48 + ;
: U.SIMPLE
    DUP 10 < IF DIGIT>CHAR EMIT
    ELSE 10 /MOD SWAP U.SIMPLE DIGIT>CHAR EMIT
    THEN ;
: PRINT-NUMBER U.SIMPLE 32 EMIT ;

: <U
    VAL_B !
    VAL_A !
    VAL_A @ UNSIGNED_MASK @ XOR
    VAL_B @ UNSIGNED_MASK @ XOR
    <
;

: D.
    SWAP
    S" High: " TYPE PRINT-NUMBER
    S" Low: " TYPE PRINT-NUMBER
    CR ;

: D+
    0 CARRY_VAR !
    A_LOW @ B_LOW @ +
    DUP A_LOW @
    <U IF
        1 CARRY_VAR !
    THEN
    A_HIGH @ B_HIGH @ + CARRY_VAR @ +
    A_LOW @ B_LOW @ + SWAP
;

2147483648 UNSIGNED_MASK !

S" --- Test 1: Addition with carry ---" TYPE CR
1 A_HIGH !
4294967295 A_LOW !
0 B_HIGH !
2 B_LOW !
D+ SWAP D. CR

S" --- Test 2: Simple addition ---" TYPE CR
0 A_HIGH !
4096 A_LOW !
0 B_HIGH !
8192 B_LOW !
D+ SWAP D. CR

HALT
